Adapt to Android31
heiher/sockstun pull request #11
Opened 2023-06-29 11:23 UTC by mosentest

2023-06-29 14:28 UTC, heiher commented
感谢你的PR，编译了这个版本并在Android 13(Arm64)系统上做了测试，初步发现了两个问题：
1. `Enable`后程序崩溃了，VPN功能无法正常工作。
2. `Apps`进入应用列表，只有部分应用可见。

2023-06-29 15:35 UTC, mosentest commented
我没验证Android13.我明天处理下吧。我只是看了Android10

2023-06-29 15:36 UTC, mosentest commented
不过我感觉不稳定啊，没在webview直接设置稳定，有的图片资源没办法请求成功，我不知道是不是网页的请求失败。还是什么原因

2023-06-29 15:42 UTC, mosentest commented
我已经增加Android31 的应用列表获取权限了，我已经忘记是Android10引入的还是，11引入的。至于闪退问题，我手机没复现，能贴下日志吗

2023-06-29 15:59 UTC, heiher commented
> 我已经增加Android31 的应用列表获取权限了，我已经忘记是Android10引入的还是，11引入的。至于闪退问题，我手机没复现，能贴下日志吗

```
06-29 23:48:47.676 25717 25717 E AndroidRuntime: java.lang.RuntimeException: Unable to start service hev.sockstun.TProxyService@62402f7 with Intent { act=hev.sockstun.CONNECT cmp=hev.sockstun/.TProxyService }: java.lang.IllegalArgumentException: hev.sockstun: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
06-29 23:48:47.676 25717 25717 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

2023-06-29 16:00 UTC, heiher commented
> 不过我感觉不稳定啊，没在webview直接设置稳定，有的图片资源没办法请求成功，我不知道是不是网页的请求失败。还是什么原因

什么不稳定？

2023-06-30 00:05 UTC, mosentest commented
> 

我晚点录制个视频

2023-06-30 00:06 UTC, mosentest commented
> > 不过我感觉不稳定啊，没在webview直接设置稳定，有的图片资源没办法请求成功，我不知道是不是网页的请求失败。还是什么原因
> 
> 什么不稳定？

我晚点录制个视频

2023-06-30 00:06 UTC, mosentest commented
> > 我已经增加Android31 的应用列表获取权限了，我已经忘记是Android10引入的还是，11引入的。至于闪退问题，我手机没复现，能贴下日志吗
> 
> ```
> 06-29 23:48:47.676 25717 25717 E AndroidRuntime: java.lang.RuntimeException: Unable to start service hev.sockstun.TProxyService@62402f7 with Intent { act=hev.sockstun.CONNECT cmp=hev.sockstun/.TProxyService }: java.lang.IllegalArgumentException: hev.sockstun: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
> 06-29 23:48:47.676 25717 25717 E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
> ```

这个已修复了

2023-06-30 01:56 UTC, heiher requested changes
Thanks for the PR.

2023-06-30 01:56 UTC, heiher commented on app/build.gradle
> +	//diff gradle.properties, when support androidx need gradle.properties
这两行注释没看懂，要不改下或移除？

2023-06-30 01:56 UTC, heiher commented on app/src/main/java/hev/sockstun/TProxyService.java
> +    // 创建通知渠道
改成英文的吧

2023-06-30 01:56 UTC, heiher commented on gradle.properties
> +android.useAndroidX=true
加个换行

2023-06-30 02:27 UTC, mosentest commented on app/build.gradle
> +	//diff gradle.properties, when support androidx need gradle.properties
配置Androidx，需用到gradle.properties。但是你写keystore又要存储在这里

2023-06-30 02:27 UTC, mosentest commented on app/src/main/java/hev/sockstun/TProxyService.java
> +    // 创建通知渠道
> 改成英文的吧

你说的是注释。我删一下

2023-06-30 02:28 UTC, mosentest commented on gradle.properties
> +android.useAndroidX=true
这Android标准不是这样写么。换行的意义在哪里？我加个注释？

2023-06-30 02:32 UTC, heiher commented on gradle.properties
> +android.useAndroidX=true
哈哈，是我没说清楚，是最后一行少一个换行。

2023-06-30 03:59 UTC, heiher commented
还有一些代码风格不一致的情况，我改一下后合入。

2023-06-30 04:42 UTC, heiher commented
Merged: https://github.com/heiher/sockstun/commit/6701cbee8d9692cee44fd477bf653b6fcd81e0f4

Thanks~

2023-06-30 04:42 UTC, closed without merging

2023-06-30 04:48 UTC, heiher commented
> > > 不过我感觉不稳定啊，没在webview直接设置稳定，有的图片资源没办法请求成功，我不知道是不是网页的请求失败。还是什么原因
> > 
> > 
> > 什么不稳定？
> 
> 我晚点录制个视频

如果是网络通过VPN后的访问性问题，我猜测可能是使用的Socks5服务器不支持UDP或是服务端不支持UDP relay over TCP但客户端选上了。建议配合 [HevSocks5Server](https://github.com/heiher/hev-socks5-server) 测一下，它同时支持两种模式。

2023-06-30 04:52 UTC, mosentest commented
> > > > 不过我感觉不稳定啊，没在webview直接设置稳定，有的图片资源没办法请求成功，我不知道是不是网页的请求失败。还是什么原因
> > > 
> > > 
> > > 什么不稳定？
> > 
> > 
> > 我晚点录制个视频
> 
> 如果是网络通过VPN后的访问性问题，我猜测可能是使用的Socks5服务器不支持UDP或是服务端不支持UDP relay over TCP但客户端选上了。建议配合 [HevSocks5Server](https://github.com/heiher/hev-socks5-server) 测一下，它同时支持两种模式。

我是购买别人的代理，这个没办法调整

2023-06-30 05:21 UTC, heiher commented
自建吧